import submitFormModel from './submitFormModel';
const {
  formField: {
    firstName,
    lastName,
    email,
    phone,
    movingDate,
    deliveryDate,
    startTime,
    originAddress,
    originCity,
    originState,
    originZip,
    originFloor,
    originApt,
    destinationAddress,
    destinationCity,
    destinationState,
    destinationZip,
    destinationFloor,
    destinationApt,
    service,
    size,
    additionalInfo,
    referral,
    isFlatRate,
    crewSize,
    estimateTime,
    estimateQuote,
    travelTime,
    timeBetween,
    distanceBetween,
  },
} = submitFormModel;

export default {
  [firstName.name]: '',
  [lastName.name]: '',
  [email.name]: '',
  [phone.name]: '',
  [movingDate.name]: '',
  [deliveryDate.name]: '',
  [startTime.name]: 'Any time',
  [service.name]: 'Moving',
  [size.name]: '',
  [additionalInfo.name]: '',
  [referral.name]: '',
  [originAddress.name]: '',
  [originCity.name]: '',
  [originState.name]: '',
  [originZip.name]: '',
  [originFloor.name]: '',
  [originApt.name]: '',
  [destinationAddress.name]: '',
  [destinationCity.name]: '',
  [destinationState.name]: '',
  [destinationZip.name]: '',
  [destinationFloor.name]: '',
  [destinationApt.name]: '',
  [isFlatRate.name]: false,
  [crewSize.name]: 0,
  [estimateTime.name]: [],
  [estimateQuote.name]: [],
  [travelTime.name]: [],
  [timeBetween.name]: 0,
  [distanceBetween.name]: 0,
};
